version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    command: sh -c "npm install && npm start"
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production